# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-11 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('author', models.CharField(max_length=64, verbose_name='作者')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('delete_status', models.IntegerField(choices=[(1, '正常'), (0, '删除')], verbose_name='删除状态')),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
