# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-12 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='delete_status',
            field=models.IntegerField(choices=[(1, '正常'), (0, '删除')], default=1, verbose_name='删除状态'),
        ),
    ]
