#!/usr/bin/env python
# -*- coding:utf-8 -*-
# __author__ = "lyon"

DJANGO_DOCS_HIDE = False

DJANGO_DOCS_ALLOWED_HOST = ['*']

DJANGO_DOCS_USERNAME = 'admin'

DJANGO_DOCS_PASSWORD = ''

DJANGO_DOCS_GLOBAL_PARAMS = []

DJANGO_DOCS_GLOBAL_HEADERS = []

INSTALLED_HANDLERS = []

INSTALLED_HANDLERS_NAME = {}
